### PR TITLE
Fix sphinx-autobuild infinite loop bug

### PR DESCRIPTION
**Pull request by bckohan**
Hey @tasansal - looks to me like its this jupyter notebook thats causing the infinite loop for sphinx-autobuild. Let me know if this works for you!

### CODE REVIEW

**Comment by tasansal** [comment]
Thanks @bckohan, I really appreciate you looking at this. I will check and merge.

This is very strange because the whole "jupyter_execute" directory is in the ignore list [here](https://github.com/TGSAI/segy/blob/6c19c09d649c73d8310429093cbf535dce41057f/docs/conf.py#L34). 

Would you mind sharing how you debug this? I've been banging my head against the wall for the past couple days :-)

I thought it was mainly due to sphinx-typer interaction based on the messages I was getting.

**Comment by bckohan** [comment]
Screenshot 2024-03-05 at 3 26 42 PM

It was calling out this file specifically - maybe exclude_patterns is ignored by sphinx-autobuild? Who knows??

Glad I could help - sometimes you just need a second pair of eyes.

**Comment by bckohan** [comment]
It does look like sphinx-autobuild ignores exclude_patterns. Here's an open PR to even fix that issue: https://github.com/sphinx-doc/sphinx-autobuild/pull/135

**Comment by tasansal** [comment]
> It does look like sphinx-autobuild ignores exclude_patterns. Here's an open PR to even fix that issue: [sphinx-doc/sphinx-autobuild#135](https://github.com/sphinx-doc/sphinx-autobuild/pull/135)

I don't know what to say, good spy craft :) Thanks a bunch again.

**Review by tasansal — APPROVED** [review]

**Pull request merged**
